import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  BriefcaseBusiness,
  CheckCircle2,
  Clock3,
  Cloud,
  Code2,
  Coffee,
  CreditCard,
  Database,
  FileText,
  Filter,
  Globe2,
  Home,
  KeyRound,
  Layers3,
  LockKeyhole,
  LucideIcon,
  Rocket,
  ShieldCheck,
  TerminalSquare,
  UsersRound,
  Webhook,
} from "lucide-react";
import type { IconName } from "@/data/developer";

export const iconMap: Record<IconName, LucideIcon> = {
  activity: Activity,
  barChart: BarChart3,
  bell: Bell,
  book: BookOpen,
  box: Box,
  briefcase: BriefcaseBusiness,
  card: CreditCard,
  check: CheckCircle2,
  clock: Clock3,
  cloud: Cloud,
  code: Code2,
  coffee: Coffee,
  database: Database,
  file: FileText,
  filter: Filter,
  globe: Globe2,
  home: Home,
  key: KeyRound,
  layers: Layers3,
  lock: LockKeyhole,
  rocket: Rocket,
  shield: ShieldCheck,
  terminal: TerminalSquare,
  users: UsersRound,
  webhook: Webhook,
};
